name: Deploy to GCP

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main
    - development

jobs:
    deploy:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: carrierpidgeon
            PROJECT_ID: invertible-vent-405318
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@main
          with:
            project_id: ${{ env.PROJECT_ID }}
    
        - name: Build Docker Image
          run: docker build -t ${{ env.IMAGE_NAME }}:latest .

        - name: Automatic Tagging of Releases
          id: increment-git-tag
          run: |
            bash ./scripts/git_update.sh -v major

        - name: Configure Docker Client
          run: |
            gcloud auth configure-docker --quiet
            gcloud auth configure-docker europe-west3-docker.pkg.dev --quiet

        - name: Push Docker Image to Container Registry (GCR)
          env: 
            GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          run: |
            docker tag ${{ env.IMAGE_NAME }}:latest gcr.io/${{env.PROJECT_ID}}/${{ env.IMAGE_NAME }}:latest
            docker tag ${{ env.IMAGE_NAME }}:latest gcr.io/${{env.PROJECT_ID}}/${{ env.IMAGE_NAME }}:${{env.GIT_TAG}}
            docker push gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:latest
            docker push gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:${{env.GIT_TAG}}
        
        - name: Push Docker Image to Artufact Registry (GCR)
          env: 
            GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
          run: |
            docker tag ${{ env.IMAGE_NAME }}:latest europe-west3-docker.pkg.dev/${{env.PROJECT_ID}}/${{ env.IMAGE_NAME }}:latest
            docker tag ${{ env.IMAGE_NAME }}:latest europe-west3-docker.pkg.dev/${{env.PROJECT_ID}}/${{ env.IMAGE_NAME }}:${{env.GIT_TAG}}
            docker push europe-west3-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:latest
            docker push europe-west3-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:${{env.GIT_TAG}}


