name: Deploy to GCP

on:
  push:
    branches:
    - main
    - development
  pull_request:
    branches:
    - main
    - development

jobs:
    deploy:
        name: Build and Push to GCP
        runs-on: ubuntu-latest
        env:
            IMAGE_NAME: carrierpidgeon
            PROJECT_ID: invertible-vent-405318
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
    
        - id: 'auth'
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_SA_KEY }}'

        - name: Set up Google Cloud SDK
          uses: google-github-actions/setup-gcloud@main
          with:
            project_id: ${{ env.PROJECT_ID }}
    
        - name: Build Docker Image
          run: docker build -t ${{ env.IMAGE_NAME }}:latest .

        - name: Configure Docker Client
          run: |
            gcloud auth configure-docker --quiet

        - name: Push Docker Image to Container Registry (GCR)
          env: 
            GIT_TAG: v0.1.0
          run: |
            docker tag ${{ env.IMAGE_NAME }}:latest gcr.io/${{env.PROJECT_ID}}/${{ env.IMAGE_NAME }}:latest
            docker tag ${{ env.IMAGE_NAME }}:latest gcr.io/${{env.PROJECT_ID}}/${{ env.IMAGE_NAME }}:${{env.GIT_TAG}}
            docker push gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:latest
            docker push gcr.io/${{env.PROJECT_ID}}/${{env.IMAGE_NAME}}:${{env.GIT_TAG}}


